# AppProject ArgoCD
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Simple Terraform K8s Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: repo-simple-terraform-k8s
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/quocnguyenx43/simple-terraform-k8s.git
  type: git
  name: simple-terraform-k8s
  username: <YOUR_GH_USERNAME>
  password: <YOUR_GH_TOKEN>
