controller:
  JCasC:
    enabled: true
    configScripts:
      credentials: |
        credentials:
          system:
            domainCredentials:
              - domain:
                  name: "global"
                  specifications: []
                credentials:
                  - usernamePassword:
                      id: "github-credentials"
                      description: "GitHub username/token"
                      username: "${GITHUB_USERNAME}"
                      password: "${GITHUB_TOKEN}"
                  - usernamePassword:
                      id: "dockerhub-credentials"
                      description: "Docker Hub username/password"
                      username: "${DOCKERHUB_USERNAME}"
                      password: "${DOCKERHUB_PASSWORD}"
