controller:
  service:
    type: NodePort
    nodePorts:
      http: 31180   # Host:80  => NodePort:31180
      https: 31443  # Host:443 => NodePort:31443
  
  # Enable metrics for Prometheus
  metrics:
    enabled: true
    service:
      annotations: {}
    serviceMonitor:
      enabled: true   # if you want the chart to create it for you
