replicaCount: 2

image:
  repository: docker.io/quocnguyenx43/prediction-app
  tag: 20251015-094947
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: prediction.localtest.me
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: ENVIRONMENT
    value: "production"
  - name: LOG_LEVEL
    value: "info"
