apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: argocd-self
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 6.8.0
      helm:
        valueFiles:
          - $values/helm/shared-values/argocd-values.yaml
    
    - repoURL: https://github.com/quocnguyenx43/simple-terraform-k8s.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
