apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/quocnguyenx43/simple-terraform-k8s
    targetRevision: master
    path: helm/shared-values
    helm:
      valueFiles:
        - argocd-values.yaml
      parameters: []
      chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 6.8.0
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
