apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: jenkins
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: 5.8.98
      helm:
        valueFiles:
          - $values/helm/shared-values/jenkins-values.yaml
    
    - repoURL: https://github.com/quocnguyenx43/simple-terraform-k8s
      targetRevision: master
      ref: values

  source:
    repoURL: https://github.com/quocnguyenx43/simple-terraform-k8s
    targetRevision: master
    path: helm/shared-values/jenkins-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
