apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: prometheus
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 62.2.0
      helm:
        valueFiles:
          - $values/helm/shared-values/prometheus-values.yaml

    - repoURL: https://github.com/quocnguyenx43/simple-terraform-k8s.git
      targetRevision: master
      ref: values

    - repoURL: https://github.com/quocnguyenx43/simple-terraform-k8s.git
      targetRevision: master
      path: manifests/monitoring
      ref: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
