apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: prediction-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: 'https://github.com/quocnguyenx43/simple-terraform-k8s.git'
    targetRevision: master
    path: helm/prediction-app
    helm:
      valueFiles:
        - ../../environments/dev/values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
