server:
  ingress:
    enabled: false
  service:
    type: ClusterIP
    ports:
      http: 80
      https: 443
  # allows HTTP access inside cluster (fine for kind)
  extraArgs:
    - --insecure
  # allowed resources
  resources:
    limits:
      cpu: "600m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"

configs:
  params:
    # allows ArgoCD UI via HTTP (no TLS proxy)
    server.insecure: "true"

controller:
  resources:
    requests:
      cpu: "250m"
      memory: "300Mi"
    limits:
      cpu: "600m"
      memory: "600Mi"

dex:
  enabled: false
