server:
  ingress:
    enabled: false
  service:
    type: ClusterIP
    ports:
      http: 80
      https: 443
  extraArgs:
    - --insecure  # allows HTTP access inside cluster (fine for kind)
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

configs:
  params:
    server.insecure: true  # allows ArgoCD UI via HTTP (no TLS proxy)

controller:
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
