grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP

alertmanager:
  enabled: true

prometheus:
  service:
    type: ClusterIP

  prometheusSpec:
    retention: 10d
